[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']

[phases.install]
cmds = [
  'npm install',
  'cd server && npm install --production=false'
]

[phases.build]
cmds = [
  'cd server && npx prisma generate --schema=./prisma/schema.prisma',
  'cd server && npm run build'
]

[start]
cmd = 'cd server && npx prisma db push --accept-data-loss && node dist/index.js'
